name: quickline_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  flutter_localizations:
    sdk: flutter
  intl: any
  intl_phone_field: ^3.2.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.15.0
  fluttertoast: ^8.2.4
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  provider: ^6.1.1
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/Background.png
    - assets/icons/apple.png
    - assets/icons/google.png

  # إذا حبيت تضيف خطوط لاحقًا فعّل هذا
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf